"""enforce one joined org per user

Revision ID: 2a4f2a066ede
Revises: cc6affc07954
Create Date: 2026-09-01 21:31:34.760366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4f2a066ede'
down_revision: Union[str, None] = 'cc6affc07954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_org_members_one_org_per_user', 'organization_members', ['user_id'], unique=True, postgresql_where=sa.text('joined_at IS NOT NULL'), sqlite_where=sa.text('joined_at IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_org_members_one_org_per_user', table_name='organization_members', postgresql_where=sa.text('joined_at IS NOT NULL'), sqlite_where=sa.text('joined_at IS NOT NULL'))
    # ### end Alembic commands ###
