"""add subscribers and subscriber lists

Revision ID: 38fe9250720d
Revises: 93ce8a25dda4
Create Date: 2026-09-27 18:10:00.000000

Pure op.create_table for three new tables (subscribers, subscriber_lists,
subscriber_list_memberships) -- no ALTER on any existing table, so this
sidesteps the batch_alter_table/bare-FK SQLite pitfalls prior migrations
(15ef3231e77f, 535e0588aa31) hit. Hand-written rather than autogenerated
(no local Postgres/full Python toolchain available in this pass) --
column types/names/constraints checked field-for-field against
models/subscriber.py and models/subscriber_list.py. Verified upgrade ->
downgrade -> upgrade against a throwaway SQLite db.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38fe9250720d'
down_revision: Union[str, None] = '93ce8a25dda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'subscribers',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=True),
        sa.Column('full_name', sa.String(length=255), nullable=True),
        sa.Column('source', sa.Enum('SIGNUP', 'NEWSLETTER_FORM', 'IMPORT', 'MANUAL', name='subscribersource'), nullable=False),
        sa.Column('status', sa.Enum('ACTIVE', 'UNSUBSCRIBED', 'BOUNCED', name='subscriberstatus'), nullable=False),
        sa.Column('marketing_consent', sa.Boolean(), nullable=False),
        sa.Column('consent_given_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('consent_source', sa.String(length=100), nullable=True),
        sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('unsubscribe_reason', sa.String(length=500), nullable=True),
        sa.Column('bounced_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('bounce_type', sa.String(length=20), nullable=True),
        sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_subscribers_user_id_users'),
        sa.PrimaryKeyConstraint('id'),
    )
    # unique=True + index=True on the model's mapped_column produces a
    # single unique index per column (not a separate UniqueConstraint
    # plus a plain index) -- matches what `alembic check` expects.
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=True)
    op.create_index(op.f('ix_subscribers_user_id'), 'subscribers', ['user_id'], unique=True)
    op.create_index(op.f('ix_subscribers_unsubscribe_token'), 'subscribers', ['unsubscribe_token'], unique=True)

    op.create_table(
        'subscriber_lists',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('is_default', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'uq_subscriber_lists_one_default', 'subscriber_lists', ['is_default'], unique=True,
        sqlite_where=sa.text('is_default = 1'), postgresql_where=sa.text('is_default = true'),
    )

    op.create_table(
        'subscriber_list_memberships',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('subscriber_list_id', sa.String(length=36), nullable=False),
        sa.Column('subscriber_id', sa.String(length=36), nullable=False),
        sa.Column('status', sa.Enum('ACTIVE', 'REMOVED', name='membershipstatus'), nullable=False),
        sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['subscriber_list_id'], ['subscriber_lists.id'], name='fk_list_memberships_subscriber_list_id_subscriber_lists'),
        sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], name='fk_list_memberships_subscriber_id_subscribers'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('subscriber_list_id', 'subscriber_id', name='uq_list_memberships_list_subscriber'),
    )
    op.create_index(op.f('ix_subscriber_list_memberships_subscriber_list_id'), 'subscriber_list_memberships', ['subscriber_list_id'], unique=False)
    op.create_index(op.f('ix_subscriber_list_memberships_subscriber_id'), 'subscriber_list_memberships', ['subscriber_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_subscriber_list_memberships_subscriber_id'), table_name='subscriber_list_memberships')
    op.drop_index(op.f('ix_subscriber_list_memberships_subscriber_list_id'), table_name='subscriber_list_memberships')
    op.drop_table('subscriber_list_memberships')

    op.drop_index('uq_subscriber_lists_one_default', table_name='subscriber_lists')
    op.drop_table('subscriber_lists')

    op.drop_index(op.f('ix_subscribers_unsubscribe_token'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_user_id'), table_name='subscribers')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.drop_table('subscribers')
