"""add organizations and organization_members

Revision ID: 535e0588aa31
Revises: 15ef3231e77f
Create Date: 2026-08-31 19:13:35.163891

Hand-adjusted after autogenerate, same fix as 15ef3231e77f: the raw
output for the new credit_transactions.organization_id column used a bare
op.create_foreign_key(None, ...)/op.drop_constraint(None, ...), which
fails on SQLite ("No support for ALTER of constraints... refer to batch
mode") and would leave an unnamed constraint on Postgres. Wrapped that one
column-add in batch_alter_table with an explicit constraint name instead;
the two new tables (plain op.create_table, no ALTER involved) are
untouched from the raw autogenerate output. Verified upgrade -> downgrade
-> upgrade against a throwaway sqlite db.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535e0588aa31'
down_revision: Union[str, None] = '15ef3231e77f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan_tier', sa.Enum('FREE', 'PRO', 'BUSINESS', 'ENTERPRISE', name='plantier'), nullable=False),
    sa.Column('credit_balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='orgrole'), nullable=False),
    sa.Column('invite_token', sa.String(length=64), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_org_members_org_email')
    )
    op.create_index(op.f('ix_organization_members_invite_token'), 'organization_members', ['invite_token'], unique=True)
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_credit_transactions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_credit_transactions_organization_id_organizations', 'organizations', ['organization_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_credit_transactions_organization_id_organizations', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_credit_transactions_organization_id'))
        batch_op.drop_column('organization_id')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_invite_token'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_table('organizations')
    # ### end Alembic commands ###
