"""add subscriptions

Revision ID: a4bb2d2f6407
Revises: 2a4f2a066ede
Create Date: 2026-09-05 17:09:02.571783

One row per user (models/subscription.py) for the Paystack-backed
recurring subscription feature. ix_subscriptions_user_id is a plain
unique index -- not the partial/conditional style
2a4f2a066ede's uq_org_members_one_org_per_user uses -- since a user is
allowed at most one Subscription row ever (cancelled or not) in this
first pass; see models/subscription.py's module docstring for why
plan-switching/resubscription is a known v2 gap rather than something
this schema accommodates yet. Raw autogenerate output, unmodified --
nothing here needed the batch_alter_table workaround 535e0588aa31's
docstring describes (a plain new table + indexes, no ALTER of an
existing one). Verified upgrade -> downgrade -> upgrade against a
throwaway sqlite db.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4bb2d2f6407'
down_revision: Union[str, None] = '2a4f2a066ede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan_key', sa.String(length=50), nullable=False),
    sa.Column('paystack_plan_code', sa.String(length=50), nullable=False),
    sa.Column('paystack_subscription_code', sa.String(length=50), nullable=True),
    sa.Column('paystack_email_token', sa.String(length=255), nullable=True),
    sa.Column('paystack_customer_code', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'PAST_DUE', 'CANCELLED', name='subscriptionstatus'), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('credits_granted_through', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_paystack_subscription_code'), 'subscriptions', ['paystack_subscription_code'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_paystack_subscription_code'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
